### ISSUE TITLE
Imputing normalized BCS...

### ISSUE THREAD

**Issue by dys1997** [cnio-bu/beyondcell#67]
When I was using beyondcell to analyze my rds data, I stopped at Imputing normalized BCS... I couldn't continue the analysis, the software did not report an error but kept running (nearly more than ten hours). My rds data is smaller than test data.It only takes about an hour for my computer to analyze the test data。

**Comment by SGMartin** [comment]
Hello @dys1997  

It is a known issue with the current version. Briefly, the KNN imputer is not converging and thus, the imputation never finishes. This is due to too many missing values for either a cell or a signature.

We are aware of this and we'll soon roll out a new version (beyondcell 2.0) adressing this issue among other improvements. 

For now, as a workaround, I would:

1. Try to subset your dataset so that at least one complete case remains for each cell/signature.
2. If you are comfortable, you can share with us your beyondcell object and we'll try to find a sensible cut-off value for the subset. 

Can you run complete.cases() over your bc@normalized matrix?
